# Kibana Configuration for WriteCareNotes Log Visualization
# Provides healthcare-focused dashboards and log analysis capabilities

apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: logging
data:
  kibana.yml: |
    server.name: writecarenotes-kibana
    server.host: "0.0.0.0"
    server.port: 5601
    server.publicBaseUrl: "https://logs.writecarenotes.com"
    
    elasticsearch.hosts: ["https://elasticsearch-client:9200"]
    elasticsearch.username: "elastic"
    elasticsearch.password: "${ELASTIC_PASSWORD}"
    elasticsearch.ssl.verificationMode: none
    
    # Security settings
    server.ssl.enabled: true
    server.ssl.certificate: /usr/share/kibana/config/certs/kibana.crt
    server.ssl.key: /usr/share/kibana/config/certs/kibana.key
    
    # Healthcare-specific settings
    logging.appenders.default:
      type: console
      layout:
        type: json
    
    # Index patterns for healthcare logs
    kibana.index: ".kibana-writecarenotes"
    
    # Security and compliance
    security.encryptionKey: "writecarenotes-kibana-encryption-key-32-chars"
    security.session.idleTimeout: "1h"
    security.session.lifespan: "8h"
    
    # Monitoring
    monitoring.enabled: true
    monitoring.kibana.collection.enabled: true
    
    # Advanced settings for healthcare compliance
    map.includeElasticMapsService: false
    telemetry.enabled: false
    newsfeed.enabled: false

---
# Kibana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.11.0
        ports:
        - containerPort: 5601
          name: http
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secrets
              key: elastic-password
        - name: NODE_OPTIONS
          value: "--max-old-space-size=2048"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        - name: certs
          mountPath: /usr/share/kibana/config/certs
          readOnly: true
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /api/status
            port: 5601
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /api/status
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
      - name: config
        configMap:
          name: kibana-config
      - name: certs
        secret:
          secretName: kibana-certs

---
# Kibana Service
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    name: http
    targetPort: 5601

---
# Kibana Certificate Secret (placeholder - generate real certs in production)
apiVersion: v1
kind: Secret
metadata:
  name: kibana-certs
  namespace: logging
type: Opaque
data:
  # These should contain real certificates in production
  kibana.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  kibana.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t

---
# Healthcare Dashboards ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-healthcare-dashboards
  namespace: logging
data:
  healthcare-operations-dashboard.json: |
    {
      "version": "8.11.0",
      "objects": [
        {
          "id": "healthcare-operations-dashboard",
          "type": "dashboard",
          "attributes": {
            "title": "WriteCareNotes - Healthcare Operations",
            "description": "Comprehensive healthcare operations monitoring dashboard",
            "panelsJSON": "[{\"version\":\"8.11.0\",\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":15,\"i\":\"1\"},\"panelIndex\":\"1\",\"embeddableConfig\":{},\"panelRefName\":\"panel_1\"}]",
            "timeRestore": true,
            "timeTo": "now",
            "timeFrom": "now-24h",
            "refreshInterval": {
              "pause": false,
              "value": 30000
            },
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"match_all\":{}},\"filter\":[]}"
            }
          }
        },
        {
          "id": "medication-administration-logs",
          "type": "search",
          "attributes": {
            "title": "Medication Administration Logs",
            "description": "All medication administration events for compliance tracking",
            "columns": ["@timestamp", "resident_id", "medication_id", "dosage", "administered_by", "correlation_id"],
            "sort": [["@timestamp", "desc"]],
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"index\":\"healthcare-logs-*\",\"query\":{\"match\":{\"event_type\":\"medication_administration\"}},\"filter\":[]}"
            }
          }
        },
        {
          "id": "compliance-violations",
          "type": "search",
          "attributes": {
            "title": "Compliance Violations",
            "description": "All compliance violations requiring immediate attention",
            "columns": ["@timestamp", "violation_type", "severity", "resident_id", "service", "message"],
            "sort": [["@timestamp", "desc"]],
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"index\":\"healthcare-logs-*\",\"query\":{\"match\":{\"event_type\":\"compliance_violation\"}},\"filter\":[]}"
            }
          }
        },
        {
          "id": "resident-admissions",
          "type": "search",
          "attributes": {
            "title": "Resident Admissions",
            "description": "All resident admission events",
            "columns": ["@timestamp", "resident_id", "nhs_number", "care_level", "service"],
            "sort": [["@timestamp", "desc"]],
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"index\":\"healthcare-logs-*\",\"query\":{\"match\":{\"event_type\":\"resident_admission\"}},\"filter\":[]}"
            }
          }
        },
        {
          "id": "audit-trail-search",
          "type": "search",
          "attributes": {
            "title": "Audit Trail",
            "description": "Comprehensive audit trail for regulatory compliance",
            "columns": ["@timestamp", "user_id", "action", "resource_type", "resource_id", "tenant_id"],
            "sort": [["@timestamp", "desc"]],
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"index\":\"audit-logs-*\",\"query\":{\"match_all\":{}},\"filter\":[]}"
            }
          }
        }
      ]
    }

  compliance-monitoring-dashboard.json: |
    {
      "version": "8.11.0",
      "objects": [
        {
          "id": "compliance-monitoring-dashboard",
          "type": "dashboard",
          "attributes": {
            "title": "WriteCareNotes - Compliance Monitoring",
            "description": "Regulatory compliance monitoring for CQC, Care Inspectorate, CIW, RQIA",
            "panelsJSON": "[{\"version\":\"8.11.0\",\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":15,\"i\":\"1\"},\"panelIndex\":\"1\",\"embeddableConfig\":{},\"panelRefName\":\"panel_1\"}]",
            "timeRestore": true,
            "timeTo": "now",
            "timeFrom": "now-7d",
            "refreshInterval": {
              "pause": false,
              "value": 60000
            },
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"match_all\":{}},\"filter\":[]}"
            }
          }
        }
      ]
    }

---
# Index Patterns ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-index-patterns
  namespace: logging
data:
  healthcare-logs-pattern.json: |
    {
      "version": "8.11.0",
      "objects": [
        {
          "id": "healthcare-logs-*",
          "type": "index-pattern",
          "attributes": {
            "title": "healthcare-logs-*",
            "timeFieldName": "@timestamp",
            "fields": "[{\"name\":\"@timestamp\",\"type\":\"date\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"level\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"message\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":false},{\"name\":\"service\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"user_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"tenant_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"correlation_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"event_type\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"compliance_level\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"resident_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"medication_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true}]"
          }
        }
      ]
    }

  audit-logs-pattern.json: |
    {
      "version": "8.11.0",
      "objects": [
        {
          "id": "audit-logs-*",
          "type": "index-pattern",
          "attributes": {
            "title": "audit-logs-*",
            "timeFieldName": "@timestamp",
            "fields": "[{\"name\":\"@timestamp\",\"type\":\"date\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"user_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"action\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"resource_type\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"resource_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"tenant_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"ip_address\",\"type\":\"ip\",\"searchable\":true,\"aggregatable\":true}]"
          }
        }
      ]
    }