# Alertmanager Configuration
# Routes alerts to appropriate channels (email, Slack, PagerDuty, etc.)

global:
  resolve_timeout: 5m
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: 'alerts@writecarenotes.com'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASS}'
  smtp_require_tls: true

# Route tree
route:
  receiver: 'default'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
      repeat_interval: 5m

    # Warning alerts - less frequent
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 1h

    # Info alerts - daily digest
    - match:
        severity: info
      receiver: 'info-alerts'
      repeat_interval: 24h

# Receivers (notification endpoints)
receivers:
  # Default receiver
  - name: 'default'
    email_configs:
      - to: 'ops@writecarenotes.com'
        headers:
          Subject: '[AlertManager] {{ .GroupLabels.alertname }}'

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'ops@writecarenotes.com,oncall@writecarenotes.com'
        headers:
          Subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
        html: |
          <h2>🚨 CRITICAL ALERT</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <p><strong>Time:</strong> {{ .StartsAt }}</p>
    
    # Uncomment to add Slack
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#critical-alerts'
    #     title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
    #     text: '{{ .CommonAnnotations.description }}'
    
    # Uncomment to add PagerDuty
    # pagerduty_configs:
    #   - service_key: 'YOUR_PAGERDUTY_KEY'
    #     description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'

  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: 'ops@writecarenotes.com'
        headers:
          Subject: '[WARNING] {{ .GroupLabels.alertname }}'
        html: |
          <h2>⚠️ WARNING ALERT</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <p><strong>Time:</strong> {{ .StartsAt }}</p>

  # Info alerts
  - name: 'info-alerts'
    email_configs:
      - to: 'ops@writecarenotes.com'
        headers:
          Subject: '[INFO] {{ .GroupLabels.alertname }}'

# Inhibition rules (suppress certain alerts when others are firing)
inhibit_rules:
  # Suppress warning alerts when critical alert is active
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
