# NGINX Ingress Controller for WriteCareNotes
# Handles external traffic management with SSL termination and load balancing

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      replicaCount: 3
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 500m
          memory: 256Mi
      config:
        # Healthcare-specific security headers
        add-headers: "ingress-nginx/custom-headers"
        # Enable real IP forwarding for audit trails
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        # SSL configuration for healthcare compliance
        ssl-protocols: "TLSv1.2 TLSv1.3"
        ssl-ciphers: "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
        # Rate limiting for API protection
        rate-limit: "1000"
        rate-limit-window: "1m"
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account:certificate/cert-id"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx
data:
  # Healthcare compliance headers
  X-Frame-Options: "DENY"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"
  Strict-Transport-Security: "max-age=31536000; includeSubDomains"
  Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
  Referrer-Policy: "strict-origin-when-cross-origin"
  # GDPR compliance headers
  X-Robots-Tag: "noindex, nofollow"