apiVersion: v1
kind: ConfigMap
metadata:
  name: writecarenotes-config
  namespace: writecarenotes
data:
  NODE_ENV: "production"
  PORT: "3000"
  API_BASE_URL: "https://api.writecarenotes.com"
  FRONTEND_URL: "https://writecarenotes.com"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  HEALTH_CHECK_INTERVAL: "30000"
  HEALTH_CHECK_TIMEOUT: "5000"
  MAX_CONNECTIONS: "100"
  CONNECTION_TIMEOUT: "30000"
  REQUEST_TIMEOUT: "30000"
  SECURITY_HEADERS_ENABLED: "true"
  CSP_ENABLED: "true"
  HSTS_ENABLED: "true"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  SESSION_MAX_AGE: "86400000"
  GDPR_DATA_RETENTION_DAYS: "2555"
  AUDIT_LOG_RETENTION_DAYS: "2555"
  BACKUP_SCHEDULE: "0 2 * * *"
  BACKUP_RETENTION_DAYS: "30"
  ENABLE_AI_AGENTS: "true"
  ENABLE_VOICE_ASSISTANT: "true"
  ENABLE_IOT_INTEGRATION: "true"
  ENABLE_PREDICTIVE_HEALTH: "true"